HOST = 0.0.0.0
PORT = 7000

export FLASK_APP = $(PWD)/app.py
export FLASK_ENV=development
export REQUIREMENTS = $(PWD)/requirements.txt

PYTHON_VERSION ?= python
VENV = $(PWD)/.venv
PYTHON = $(VENV)/bin/python
PIP = $(VENV)/bin/pip
FLASK = $(VENV)/bin/flask
